name: Manual Filepath Metadata Sync

on:
  repository_dispatch:
    types: [metadata_file_update]

permissions:
  id-token: write
  contents: write

env:
  MOVIE_METADATA_FILE: movie-metadata.yml
  SHOW_METADATA_FILE: show-metadata.yml
  JSON_DATA_FILE: json-data.json
  ARTIFACT_NAME: json-data

jobs:
  update:
    name: Update Metadata Files
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.commit-changes.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Save JSON Data to a File
        id: json-to-file
        run: |
          echo '${{ toJSON(github.event.client_payload.data) }}' > ${{ env.JSON_DATA_FILE }}

      - name: Upload JSON File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.JSON_DATA_FILE }}
