name: Manually add Media
run-name: Manually add ${{ inputs.media_type }} ${{ inputs.title }}

on:
  workflow_dispatch:
    inputs:
      media_type:
        description: Media Type
        required: true
        type: choice
        options:
          - movie
          - show
      txdb_id:
        description: TMDb or TVDb ID
        required: true
        type: string
      title:
        description: Title
        required: true
        type: string
      release_year:
        description: Release Year
        required: true
        type: string
      url_poster:
        description: Poster URL
        required: true
        type: string
      genres:
        description: Genres, Comma Spaced
        required: true
        type: string
      studio:
        description: Studio
      seasons:
        description: Seasons, Comma Spaced
        type: string

permissions:
  id-token: write
  contents: write

env:
  MEDIA_TYPE: ${{ inputs.media_type }}
  TXDB_ID: ${{ inputs.txdb_id }}
  TITLE: ${{ inputs.title }}
  RELEASE_YEAR: ${{ inputs.release_year }}
  URL_POSTER: ${{ inputs.url_poster }}
  GENRES_COMMA_SPACED: ${{ inputs.genres }}
  SEASONS_COMMA_SPACED: ${{ inputs.seasons }}
  STUDIO: ${{ inputs.studio }}
  MOVIE_METADATA_FILE: movie-metadata.yml
  SHOW_METADATA_FILE: show-metadata.yml
  UPDATE_SUMMARY_FILE: metadata_updates.md

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.commit-changes.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set METADATA_FILE
        run: |
          if [[ "$MEDIA_TYPE" == "movie" ]]; then
              echo "METADATA_FILE=$MOVIE_METADATA_FILE" >> $GITHUB_ENV
          else
              echo "METADATA_FILE=$SHOW_METADATA_FILE" >> $GITHUB_ENV
          fi
      
      - name: Update metadata file with media information
        run: |
          bash "functions/yaml/insert-media-item.sh" \
            "$MEDIA_TYPE" \
            "$TXDB_ID" \
            "$TITLE" \
            "$RELEASE_YEAR" \
            "$URL_POSTER" \
            "$GENRES_COMMA_SPACED" \
            "$SEASONS_COMMA_SPACED" \
            "$STUDIO" \
            "$METADATA_FILE"

      - name: Sort and format metadata files
        run: |
          # Sort and format the metadata file
          bash "functions/yaml/sort-metadata-file.sh" "$METADATA_FILE"
          bash "functions/yaml/format-metadata-file.sh" "$METADATA_FILE"
      
      - name: Commit Changes to Main
        id: commit-changes
        run: |
          bash "functions/git/set-git-config.sh"
          sha=$(bash "functions/git/commit-with-summary.sh" \
                  "Updating $TITLE ($RELEASE_YEAR)" \
                  "$UPDATE_SUMMARY_FILE" \
                  "$METADATA_FILE")
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: Create Job Summary
        run: |
          echo "## Metadata Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          cat "$UPDATE_SUMMARY_FILE" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
