name: Sort and Format Metadata Files

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  MOVIE_METADATA_FILE: movie-metadata.yml
  SHOW_METADATA_FILE: show-metadata.yml
  UPDATE_SUMMARY_FILE: metadata_updates.md

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Sort metadata files
        run: |
          bash "functions/yaml/sort-metadata-file.sh" "$MOVIE_METADATA_FILE"
          bash "functions/yaml/sort-metadata-file.sh" "$SHOW_METADATA_FILE"
      
      - name: Format metadata files
        run: |
          bash "functions/yaml/format-metadata-file.sh" "$MOVIE_METADATA_FILE"
          bash "functions/yaml/format-metadata-file.sh" "$SHOW_METADATA_FILE"
      
      - name: Commit Changes to Main
        id: commit-changes
        run: |
          bash "functions/git/set-git-config.sh"
          sha=$(bash "functions/git/commit-with-summary.sh" \
                  "Sorted and Formatted Metadata Files" \
                  "$UPDATE_SUMMARY_FILE" \
                  "$MOVIE_METADATA_FILE" \
                  "$SHOW_METADATA_FILE")
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: Create Job Summary
        run: |
          echo "## Metadata Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          cat "$UPDATE_SUMMARY_FILE" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
